baseURL = 'http://prakashydv.github.io/hsyadav'
languageCode = 'en-us'
title = 'H.S. Yadav'
theme = 'ananke'
description = 'Thoughts and Recollections by Hari Shanker Yadav'
ogimage = '/static/ogimg.png'
favicon = '/static/favicon.ico'